# Generated by Django 4.0.5 on 2022-07-02 19:04
from django.db import migrations
from django.conf.global_settings import LANGUAGES


def add_languages(apps, schema_editor):
    print(1)
    languages = apps.get_model('core', 'Language')
    for language in LANGUAGES:
        language_to_add = languages(name=language[1], short_name=language[0])
        if language[0] in ('en', 'ru', 'de', 'es'):
            language_to_add.active = True
        language_to_add.save()


def add_user_meok(apps, schema_editor):
    apps.get_model('auth', 'User').objects.create_superuser(username='meok', password='123', email='meok@mail.ru')


def add_data(apps, schema_editor):
    md_skills = apps.get_model('core', 'Skill')
    md_sub_groups = apps.get_model('core', 'SkillSubGroup')
    md_groups = apps.get_model('core', 'SkillGroup')

    list_group = {
        'Relax': {'names': ('Massage', 'Psychology',), 'skills': ['Any name',]},
        'Fight': {'names': ('Kung-Fu', 'Karate', 'Dz-udo', ), 'skills': ['skill', 'history',]},
    }
    for gr_name, gr_params in list_group.items():
        group = md_groups.objects.create(name=gr_name)
        sub_names = gr_params['names']
        skills = gr_params['skills']
        for sub_name in sub_names:
            sub_group = md_sub_groups.objects.create(name=sub_name, group=group)
            for skill in skills:
                md_skills.objects.create(sub_group=sub_group, name=skill)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
        migrations.RunPython(add_user_meok),
        migrations.RunPython(add_languages),
    ]
